### ISSUE TITLE
Not quite ready for chef 13

### ISSUE THREAD

**Issue by ghost** [johnko-chef/sysrc#1]
This warning has started popping up as of chef 12.4.1:
- sysrc[hostname] action create[2015-09-11T11:30:56+00:00] WARN: Class Chef::Provider::Sysrc does not declare 'resource_name :sysrc'.
     [2015-09-11T11:30:56+00:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.

It should probably have a fix before chef 13 is out.

**Comment by johnko** [comment]
Could you test on a non-production system and see if a5abd37 fixes it?

**Comment by ghost** [comment]
Doesn't fix it, sadly. I suspect from https://github.com/chef/chef/issues/3614 that the error message is entirely inaccurate, but a quick local test specifying "provides" as well also fails, so I'm not sure what to make of it.

**Comment by johnko** [comment]
@Sousaphone d'oh. Maybe I put it in the wrong file. I think I should have edited `libraries/provider_sysrc.rb` instead???

**Comment by johnko** [comment]
See if 8308c53 does the trick. You might have to undo the last change, or just checkout the dev2 branch at https://github.com/johnko-chef/sysrc/tree/dev2

**Comment by ghost** [comment]
8308c53 fixes the issue and makes sysrc chef 13 ready.

**Comment by johnko** [comment]
Merged. Thanks @Sousaphone for trying it out.
